import { MonolithFactory, type MonolithFactoryOptions } from "./monolith-factory.js";

export const CURRENT_EVOLUTION_BASELINE = Object.freeze({
  highestRecordedPass: 192,
  label: "Pass 192 + runtime hardening",
  runtimeHardeningDecision: "ADR-082",
});

/** Exact composition contract for the current evolution baseline. */
export const CURRENT_REQUIRED_COMPONENTS = [
  "acpBridgeServer",
  "acpPermissionGate",
  "acpProtocolCodec",
  "acpSnapshotManager",
  "acpToolSuite",
  "agentEngine",
  "anchoredCronJobManager",
  "anchoredSkillMutator",
  "anchoredSoulMutator",
  "anchoredWorktreeManager",
  "antiDegenerationGuard",
  "approvalHashLedger",
  "arbiterSnapshotManager",
  "arbiterToolSuite",
  "argumentCoercer",
  "atomicMutationSupervisor",
  "authStorageVault",
  "batchAnchorer",
  "benchmarkEvaluator",
  "broccoliAcpSubstrate",
  "broccoliApprovalPolicyEngine",
  "broccoliArbiterSubstrate",
  "broccoliArchitectureProfiler",
  "broccoliAxiomVerifier",
  "broccoliBlastRadiusCalculator",
  "broccoliBrowserSubstrate",
  "broccoliCASScratchpad",
  "broccoliCasCompactor",
  "broccoliCircuitBreaker",
  "broccoliCognitiveSuggestionEngine",
  "broccoliCommandDiagnostics",
  "broccoliCommandSanitizer",
  "broccoliCompressionSubstrate",
  "broccoliContextDiagnosis",
  "broccoliContractVerifier",
  "broccoliCredentialSubstrate",
  "broccoliCronSubstrate",
  "broccoliDecisionLog",
  "broccoliEnvironmentSubstrate",
  "broccoliEpistemicReasoningEngine",
  "broccoliExecutionTraceRecorder",
  "broccoliFaultSubstrate",
  "broccoliFencingMutexEngine",
  "broccoliGatewaySubstrate",
  "broccoliIntegrityOptimizer",
  "broccoliIntegrityProtocol",
  "broccoliIntentTracer",
  "broccoliInterAgentMailbox",
  "broccoliJoyRideDiagnostics",
  "broccoliJoyZoningEngine",
  "broccoliJoyZoningGuard",
  "broccoliLearningSubstrate",
  "broccoliLspBridge",
  "broccoliMcpSubstrate",
  "broccoliModeController",
  "broccoliModuleDecomposer",
  "broccoliMutationPlanner",
  "broccoliOutputBuffer",
  "broccoliPatchSubstrate",
  "broccoliPlanEnforcer",
  "broccoliProcessSubstrate",
  "broccoliQueryLoop",
  "broccoliReactiveObserver",
  "broccoliRepairMutationExecutor",
  "broccoliRetentionCleanup",
  "broccoliRollbackCoordinator",
  "broccoliSearchSubstrate",
  "broccoliSemanticAxiom",
  "broccoliShellResolver",
  "broccoliSideQuery",
  "broccoliSimulation",
  "broccoliSoulSubstrate",
  "broccoliSpiderAuditEngine",
  "broccoliStabilityForensics",
  "broccoliStreamingToolExecutor",
  "broccoliStructuralDiscovery",
  "broccoliSubstrateStore",
  "broccoliSystemInvariantEngine",
  "broccoliTaskCoordinator",
  "broccoliTaskDagScheduler",
  "broccoliTaskStateEngine",
  "broccoliTokenEstimator",
  "broccoliTspPolicy",
  "broccoliUniversalGuard",
  "broccoliVerificationPipeline",
  "browserSnapshotManager",
  "budgetCalculator",
  "cdpDialogPolicyEngine",
  "cdpDomSnapshotter",
  "cdpNavigationGuard",
  "cdpProtocolClient",
  "cdpSupervisorEngine",
  "cdpToolSuite",
  "centennialPassMarker",
  "checkpointDigest",
  "clipboardBridge",
  "codexOAuthManager",
  "codexProviderBridge",
  "commandPathResolver",
  "commitGenerator",
  "completionGate",
  "compressionSnapshotManager",
  "compressionToolSuite",
  "config",
  "connectionController",
  "continuousLearningCurator",
  "convergenceEngine",
  "credentialCircuitBreaker",
  "credentialSnapshotManager",
  "credentialToolSuite",
  "cronLifecycleGuard",
  "cronSnapshotManager",
  "cronToolSuite",
  "deterministicBlueprintCatalog",
  "deterministicCredentialPool",
  "deterministicErrorClassifier",
  "deterministicPatchEngine",
  "deterministicSessionSearchEngine",
  "deterministicSkillCurator",
  "deterministicSoulParser",
  "deterministicToolPruner",
  "diffSynthesizer",
  "discordProtocolAdapter",
  "dockerEnvironmentAdapter",
  "dynamicModelCache",
  "ears",
  "envKeyResolver",
  "environmentSnapshotManager",
  "environmentSupervisorEngine",
  "environmentToolSuite",
  "evolutionarySkillEngine",
  "eyes",
  "faultDiagnosticToolSuite",
  "faultRecoverySupervisor",
  "faultSnapshotManager",
  "fileLockManager",
  "fileMutationToolSuite",
  "filePeeker",
  "frontmatterParser",
  "ftsQuerySanitizer",
  "gatewayDeliveryLedger",
  "gatewayDispatcherEngine",
  "gatewayServer",
  "gatewaySessionRegistry",
  "gatewaySnapshotManager",
  "gatewayToolSuite",
  "gitIgnoreFilter",
  "hands",
  "headTailBudgetGovernor",
  "httpDispatcher",
  "ignoreController",
  "imageModelRegistry",
  "intelligenceEngine",
  "interactiveController",
  "interactiveSecurityArbiter",
  "jitteredBackoffGovernor",
  "joyrideCache",
  "keybindingsController",
  "knowledgeGraph",
  "languageSyntaxParser",
  "learningCuratorToolSuite",
  "learningSnapshotManager",
  "localEnvironmentAdapter",
  "lockAuthorityEngine",
  "loopHarness",
  "loopPhaseController",
  "masterBenchmarkOrchestrator",
  "mcpClientToolSuite",
  "mcpHub",
  "mcpSecurityScrubber",
  "mcpSnapshotManager",
  "mcpSupervisorEngine",
  "mcpTransportCodec",
  "mentionResolver",
  "modelCatalog",
  "modelResolver",
  "monolithCredentialManager",
  "monolithCronScheduler",
  "monolithSwarmDelegator",
  "mutationSubstrate",
  "patchSnapshotManager",
  "permissionController",
  "postmortemDiagnostic",
  "processLifecycleManager",
  "processOutputRingBuffer",
  "processSecuritySandbox",
  "processSnapshotManager",
  "processSupervisorEngine",
  "processToolSuite",
  "promptComposer",
  "providerAttribution",
  "proxyGateway",
  "reasoningEffortController",
  "resilientFetchClient",
  "ringBuffer",
  "ripgrepSearchService",
  "schemaValidator",
  "searchSnapshotManager",
  "searchToolSuite",
  "secretScrubber",
  "securityRiskClassifier",
  "semanticKnowledgeGraph",
  "semverComparator",
  "sessionCompactor",
  "sessionContext",
  "sessionMemoryStore",
  "sessionStore",
  "sessionVfs",
  "setupWizard",
  "skillsIngestor",
  "skillTreeParser",
  "skillTreePromptComposer",
  "skillTreeSnapshotManager",
  "skillTreeSubstrate",
  "skillTreeToolSuite",
  "slackProtocolAdapter",
  "slashRouter",
  "snapcompactEngine",
  "snapshotLruCache",
  "snapshotStorageIndex",
  "snowflakeIdGenerator",
  "soulPromptComposer",
  "soulSnapshotManager",
  "soulThreatGuard",
  "soulToolSuite",
  "stabilityDoctor",
  "stalenessTracker",
  "stderrGuard",
  "streamFormatter",
  "subagentBudgetGovernor",
  "subagentLifecycleGuard",
  "subagentVfsBrancher",
  "swarmDispatcher",
  "swarmToolSuite",
  "systemDirectoryResolver",
  "systemHealthAggregator",
  "tabSpacingNormalizer",
  "telegramProtocolAdapter",
  "telemetryTracer",
  "templateEngine",
  "textSanitizer",
  "timingBuffer",
  "tokenBucketRateGovernor",
  "tokenTruncator",
  "toolRegistry",
  "trajectoryCompactorEngine",
  "treeWalker",
  "ttsrCoordinator",
  "urlContentFetcher",
  "variableInjector",
  "webhookProtocolAdapter",
  "writeCoalescer",
] as const satisfies readonly (keyof ReturnType<typeof MonolithFactory.createEngine>)[];

export interface CompositionVerification {
  baseline: typeof CURRENT_EVOLUTION_BASELINE;
  cohesionStatus: "OPTIMAL" | "DEGRADED";
  componentCount: number;
  requiredComponentCount: number;
  missingComponents: string[];
  unexpectedComponents: string[];
  duplicateManifestComponents: string[];
}

/** Verifies the current capability baseline rather than trusting a pass counter. */
export class GrandMonolithSynthesizer {
  static verifyComposition(components: object): CompositionVerification {
    const componentRecord = components as Record<string, unknown>;
    const missingComponents = CURRENT_REQUIRED_COMPONENTS.filter(
      (component) => !Object.hasOwn(components, component) || componentRecord[component] == null
    );
    const requiredComponents = new Set<string>();
    const duplicateManifestComponents: string[] = [];
    for (const component of CURRENT_REQUIRED_COMPONENTS) {
      if (requiredComponents.has(component)) duplicateManifestComponents.push(component);
      requiredComponents.add(component);
    }
    const unexpectedComponents = Object.keys(components).filter((component) => !requiredComponents.has(component));

    return {
      baseline: CURRENT_EVOLUTION_BASELINE,
      cohesionStatus: missingComponents.length === 0
        && unexpectedComponents.length === 0
        && duplicateManifestComponents.length === 0
        ? "OPTIMAL"
        : "DEGRADED",
      componentCount: Object.keys(components).length,
      requiredComponentCount: CURRENT_REQUIRED_COMPONENTS.length,
      missingComponents,
      unexpectedComponents,
      duplicateManifestComponents,
    };
  }

  /** @deprecated Prefer `verifyComposition()` with the active monolith components. */
  static verifyAllPasses(options: MonolithFactoryOptions = {}): CompositionVerification & { passCount: number } {
    const verification = this.verifyComposition(MonolithFactory.createEngine(options));
    return {
      ...verification,
      passCount: CURRENT_EVOLUTION_BASELINE.highestRecordedPass,
    };
  }
}
